### ISSUE TITLE
請教 jumpThreshold 用法

### ISSUE THREAD

**Issue by kevinstyle** [hi-dhl/AndroidX-Jetpack-Practice#1]
請教一下PagingConfig內的jumpThreshold用法? 我設定了jumpThreshold後運行報錯，要我覆寫pagingSource.jumpingSupported，具體錯誤碼在PageFetcherSnapshot的init代碼裡面

**Comment by hi-dhl** [comment]
你好，能贴一下你的错误日志吗，以及这块的代码，感谢
