### ISSUE TITLE
paging3网络结合数据库一起的用法建议出一下。

### ISSUE THREAD

**Issue by Petterpx** [hi-dhl/AndroidX-Jetpack-Practice#3]
现在的数据库读取本质依然是和网络读取那一套一致。

**Comment by hi-dhl** [comment]
paging3网络结合数据库一起的用法，参考我写的另外一篇文章，已经同步到 公众号 和 掘金

* 公众号 [Jetpack成员Paging3获取网络分页数据并更新到数据库中（三)](https://mp.weixin.qq.com/s/ABtWRiiIKlQe32Z6sFPbng) 
* 掘金地址：https://juejin.im/post/6854573220457086990

这两篇文章内容都是一样的，核心 RemoteMediator 结合 PagingSource 一起使用

**Comment by Petterpx** [comment]
好的，非常感谢
