### ISSUE TITLE
项目打开方式

### ISSUE THREAD

**Issue by Quyunshuo** [hi-dhl/AndroidX-Jetpack-Practice#4]
弱弱的问一句这种项目的结构  应该怎么打开  我用as直接通过git拉取这个项目  但是由于目录里的第一级仍然是peoject级别的  所以无法运行  我本是想看看Composing builds是怎么在项目里使用的  但是我感觉我无法正确的进行版本控制 因为它和项目属于同级别

**Comment by hi-dhl** [comment]
Composing builds 就是要放在同一级别的

![image](https://user-images.githubusercontent.com/16751752/100690114-d2e6a380-33c0-11eb-90ec-16f3759e5476.png)

打开图片当中的任意一个项目，gradle 会自动编译，等待编译完成就可以了

**Comment by Quyunshuo** [comment]
也就是说 不能直接通过as 拉取并打开这个项目

**Comment by hi-dhl** [comment]
目前这个仓库，下面的每个项目，都对应 Jetpack 成员的一种用法 ， 也不是不能，需要进行一些配置，目前为了方便查看，没有做这方面的配置，如果只是想查看 Composing builds 的用法，随便打开一个项目就可以看到了， 这个仓库下面的所有项目，都引用的 Composing builds（VersionPlugin）来管理所有依赖的

**Comment by Quyunshuo** [comment]
了解了
