### ISSUE TITLE
不应该是sample

### ISSUE THREAD

**Issue by qingmiaodi521** [hi-dhl/AndroidX-Jetpack-Practice#5]
打扰打扰，强迫症患者。simple和sample

**Comment by hi-dhl** [comment]
sample： 样本、案例 、 demo 等等意思
simple：简单 、容易等等意思，换句话说，每个项目对应一种技术 、一种场景，演示了每个技术在实际项目中简单的使用

例如：Paging 3 加载本地数据库 、 Paging 3 加载网络数据 等等 都对应的一种场景

**Comment by hi-dhl** [comment]
所以名字后面就都跟着 simple 了

**Comment by qingmiaodi521** [comment]
soga
