### ISSUE TITLE
Simple 是什么鬼？不是sample吗？

### ISSUE THREAD

**Issue by zhangjun725** [hi-dhl/AndroidX-Jetpack-Practice#7]

**Comment by hi-dhl** [comment]
sample： 样本、案例 、 demo 等等意思，可能包含多个技术混合一起用。

simple：简单 、容易等等意思，换句话说，每个项目对应一种技术 、一种场景，演示了每个技术在实际项目中的单独使用。

例如：Paging 3 加载本地数据库 、 Paging 3 加载网络数据 等等都对应的一种场景，分成了独立项目，便于查看

**Comment by hi-dhl** [comment]
非常感谢你的提交，我将要关闭这个 issue， 如果有任何问题，欢迎你再次提交。

**Comment by langaoyang** [comment]
哈哈，笑死我了
